<a href="https://colab.research.google.com/github/shribiyani/TensorFlow-Practice/blob/main/Tensorflow_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import tensorflow as tf

In [8]:
# Load MNIST dataset
mnist = tf.keras.datasets.mnist
mnist

<module 'tensorflow.keras.datasets.mnist' from '/usr/local/lib/python3.6/dist-packages/tensorflow/keras/datasets/mnist/__init__.py'>

In [9]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [10]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [11]:
# to build sequantial model by using stacking layer

model = tf.keras.models.Sequential([
                                    tf.keras.layers.Flatten(input_shape = (28, 28)),
                                    tf.keras.layers.Dense(128, activation = 'relu'),
                                    tf.keras.layers.Dropout(0.2),
                                    tf.keras.layers.Dense(10)
])

model

For each example the model returns a vector of "logits" or "log-odds" scores, one for each class.

In [13]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.363958  ,  0.58903754,  0.18660556, -0.5261624 ,  0.00587427,
         0.14702988,  0.00664912,  0.0222006 , -0.88628006,  0.5527627 ]],
      dtype=float32)

In [14]:
# tf.nn.softmax > function converts these logits to "probabilities" for each class -

tf.nn.softmax(predictions).numpy()

array([[0.12644088, 0.15835738, 0.10589229, 0.05191743, 0.08838402,
        0.10178337, 0.08845253, 0.08983885, 0.03621729, 0.15271594]],
      dtype=float32)

In [15]:
# losses.SparseCategoricalCrossentropy > loss takes a vector of logits and a True index and returns a scalar loss for each example.

loss_func = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)
loss_func

This loss is equal to the negative log probability of the true class: It is zero if the model is sure of the correct class.

This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.log(1/10) ~= 2.3.

In [17]:
loss_func(y_train[: 1], predictions).numpy()

2.2849085

In [18]:
model.compile(optimizer = 'adam', loss = loss_func, metrics = ['accuracy'])

# Model.fit > adjusts the model parameters to minimize the loss:

model.fit(x_train, y_train, epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4811 - accuracy: 0.8599
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1527 - accuracy: 0.9549
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1097 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0889 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0780 - accuracy: 0.9766


In [19]:
# Model.evaluate >checks the models performance, usually on a "Validation-set" or "Test-set".

model.evaluate(x_test, y_test, verbose = 2)

313/313 - 0s - loss: 0.0784 - accuracy: 0.9752


[0.07843140512704849, 0.9751999974250793]

In [22]:
# If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

probability_model = tf.keras.Sequential([
                                         model,
                                        tf.keras.layers.Softmax()
])

# checking model probability
probability_model(x_test[:])

<tf.Tensor: shape=(10000, 10), dtype=float32, numpy=
array([[1.0821308e-07, 1.9974424e-08, 4.1998219e-06, ..., 9.9971575e-01,
        4.6399559e-06, 1.0825159e-05],
       [2.2435783e-08, 9.4760479e-05, 9.9990189e-01, ..., 2.4570930e-14,
        1.6460912e-06, 6.7540781e-14],
       [9.9394117e-07, 9.9906844e-01, 1.0301385e-04, ..., 3.7191223e-04,
        3.0200253e-04, 1.1576260e-06],
       ...,
       [1.4203020e-14, 1.4080736e-12, 1.5553733e-12, ..., 4.0728798e-07,
        9.7807811e-07, 2.4654219e-05],
       [1.6108419e-08, 8.9763805e-09, 4.2332846e-11, ..., 9.7996766e-10,
        5.9050551e-05, 2.9140561e-11],
       [9.4283692e-10, 1.0255476e-14, 9.6537844e-09, ..., 2.0750424e-12,
        6.0767402e-10, 8.3425549e-12]], dtype=float32)>